[2024-06-14T04:15:00.880+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T04:15:00.898+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready scheduled__2024-06-13T22:40:00+00:00 [queued]>
[2024-06-14T04:15:00.906+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready scheduled__2024-06-13T22:40:00+00:00 [queued]>
[2024-06-14T04:15:00.906+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-14T04:15:00.926+0530] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2024-06-13 22:40:00+00:00
[2024-06-14T04:15:00.929+0530] {standard_task_runner.py:63} INFO - Started process 128340 to run task
[2024-06-14T04:15:00.932+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'is_weather_api_ready', 'scheduled__2024-06-13T22:40:00+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmptfs9jzid']
[2024-06-14T04:15:00.934+0530] {standard_task_runner.py:91} INFO - Job 201: Subtask is_weather_api_ready
[2024-06-14T04:15:00.999+0530] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.is_weather_api_ready scheduled__2024-06-13T22:40:00+00:00 [running]> on host AlexMercer99.
[2024-06-14T04:15:01.125+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alex99mercer26263@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T22:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T22:40:00+00:00'
[2024-06-14T04:15:01.126+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T04:15:01.136+0530] {baseoperator.py:400} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-06-14T04:15:01.137+0530] {http.py:137} INFO - Poking: /data/2.5/weather?id=1259229&appid=8edf636a18dd28a56a2469fd9c9e5196
[2024-06-14T04:15:01.150+0530] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-06-14T04:15:03.205+0530] {http.py:200} ERROR - HTTP error: Bad Gateway
[2024-06-14T04:15:03.205+0530] {http.py:201} ERROR - <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>

[2024-06-14T04:15:03.206+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T04:15:03.218+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/providers/http/hooks/http.py", line 198, in check_response
    response.raise_for_status()
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.openweathermap.org/data/2.5/weather?id=1259229&appid=8edf636a18dd28a56a2469fd9c9e5196

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/providers/http/sensors/http.py", line 164, in execute
    super().execute(context=context)
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/sensors/base.py", line 264, in execute
    raise e
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/sensors/base.py", line 246, in execute
    poke_return = self.poke(context)
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/providers/http/sensors/http.py", line 158, in poke
    raise exc
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/providers/http/sensors/http.py", line 139, in poke
    response = hook.run(
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/providers/http/hooks/http.py", line 188, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/providers/http/hooks/http.py", line 239, in run_and_check
    self.check_response(response)
  File "/home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/providers/http/hooks/http.py", line 202, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 502:Bad Gateway
[2024-06-14T04:15:03.229+0530] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=is_weather_api_ready, run_id=scheduled__2024-06-13T22:40:00+00:00, execution_date=20240613T224000, start_date=20240613T224500, end_date=20240613T224503
[2024-06-14T04:15:03.250+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 201 for task is_weather_api_ready (502:Bad Gateway; 128340)
[2024-06-14T04:15:03.275+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T04:15:03.297+0530] {logging_mixin.py:188} WARNING - /home/anandkalsait/airflow-venv/lib/python3.10/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
[2024-06-14T04:15:03.313+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T04:15:03.314+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
